#!/usr/bin/env bash
#
# setup.sh - Build the setup container and produce a self-contained web app.
#
# Usage:
#   ./setup.sh [output-dir]
#
# Arguments:
#   output-dir   Host path to write the full web app into (default: ./web)
#
# Environment:
#   APK_CACHE    Host path used to cache the downloaded APK between runs
#                (default: ./cache). Bind-mounted to /cache in the container.
#
# The output directory will mirror the repo's web/ layout:
#   output-dir/
#     index.html
#     css/
#     js/
#     data/          <- generated by the container (strings, chapters, assets)
#
# Open output-dir/index.html in a browser to run the app.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OUTPUT_DIR="${1:-$SCRIPT_DIR/web}"
mkdir -p "$OUTPUT_DIR/data"
OUTPUT_DIR="$(realpath "$OUTPUT_DIR")"

CACHE_DIR="${APK_CACHE:-$SCRIPT_DIR/cache}"
mkdir -p "$CACHE_DIR"
CACHE_DIR="$(realpath "$CACHE_DIR")"

echo "Output:    $OUTPUT_DIR"
echo "APK cache: $CACHE_DIR"
echo ""

echo "Building setup image..."
docker build -t oathsworn-setup -f "$SCRIPT_DIR/Dockerfile" "$SCRIPT_DIR"

echo ""
echo "Running setup..."
docker run --rm \
    -e HOST_UID="$(id -u)" \
    -e HOST_GID="$(id -g)" \
    -v "$OUTPUT_DIR/data:/repo/web/data:z" \
    -v "$CACHE_DIR:/cache:z" \
    oathsworn-setup

echo ""
echo "============================================================"
echo "===                    Copying Files                     ==="
echo "============================================================"
# Copy static web assets into the output directory.
# Skipped when OUTPUT_DIR is already the repo's web/ directory.
WEB_SRC="$SCRIPT_DIR/web"
if [[ "$(realpath "$OUTPUT_DIR")" != "$(realpath "$WEB_SRC")" ]]; then
    echo ""
    echo "Copying static files to $OUTPUT_DIR..."
    cp "$WEB_SRC/index.html" "$OUTPUT_DIR/"
    cp -r "$WEB_SRC/css"    "$OUTPUT_DIR/"
    cp -r "$WEB_SRC/js"     "$OUTPUT_DIR/"
fi

echo ""
echo "============================================================"
echo "===                    Setup complete                    ==="
echo "============================================================"
echo "Open: $OUTPUT_DIR/index.html in your web browser of choice to get started."
echo ""
