// Hand-authored UI strings for all languages.
// Each STRINGS["xx"] block uses Object.assign so it merges with any game
// translation file for the same language that loads later.
//
// To add a new language: copy any block below, change the language code,
// and translate each value. Game story text falls back to English
// automatically for any keys not present here.
// Run: python3 translations/gen_ui_template.py <code>  for a starter block.
window.STRINGS = window.STRINGS || {};

// ── English ──────────────────────────────────────────────────────────────────
STRINGS["en"] = Object.assign(STRINGS["en"] || {}, {
    "ui.new_campaign":         "New Campaign",
    "ui.continue_campaign":    "Continue Campaign",
    "ui.might_decks":          "Might Decks",
    "ui.view_saved_data":      "View Saved Data",
    "ui.settings":             "Settings",
    "ui.back":                 "Back",
    "ui.select_chapter":       "Select Chapter",
    "ui.saved_data":           "Saved Data",
    "ui.copy_json":            "Copy JSON",
    "ui.exit_chapter_select":  "Exit to Chapter Select",
    "ui.bug_report":           "Bug Report",
    "ui.auto_scroll":          "Auto Scroll",
    "ui.auto_scroll_desc":     "Scroll the page automatically as narration plays. Scrolling manually will disable it for the current section.",
    "ui.auto_narration":       "Auto Start Narration",
    "ui.auto_narration_desc":  "Begin playing narration automatically when a new section loads.",
    "ui.auto_next":            "Auto Play Next Track",
    "ui.auto_next_desc":       "Advance to the next audio track automatically when one finishes.",
    "ui.language":             "Language",
    "ui.language_desc":        "Switch the story text and interface language. Falls back to English for any missing keys.",
    "ui.file_bug_report":      "File a Bug Report",
    "ui.bug_instructions":     "Copy the debug info below and paste it into a new GitHub issue:",
    "ui.copy_to_clipboard":    "Copy to Clipboard",
    "ui.scroll_more":          "scroll for more",
    "ui.autoscroll_paused":    "Auto-scroll paused \u00b7 click to resume",
    "ui.draw_history":         "Draw History",
    "ui.reshuffle_all":        "Reshuffle All",
    "ui.clear":                "Clear",
    "ui.draw_more":            "Draw More",
    "ui.clear_and_draw":       "Clear & Draw",
    "ui.history":              "History",
    "ui.clear_history":        "Clear History",
    // Chapter taglines shown in the chapter select screen
    "ui.tagline_1":  "The road winds into the dark wood...",
    "ui.tagline_2":  "A gathering at the Broken Oak...",
    "ui.tagline_3":  "Calm before the storm...",
    "ui.tagline_4":  "Lost and hunted...",
    "ui.tagline_5":  "A desperate retreat...",
    "ui.tagline_6":  "Something stirs beneath the skin...",
    "ui.tagline_7":  "A grim march...",
    "ui.tagline_8":  "Victory that feels like defeat...",
    "ui.tagline_9":  "Weary and scarred...",
    "ui.tagline_10": "Trapped...",
    "ui.tagline_11": "Old grudges...",
    "ui.tagline_22": "A special encounter...",
    "ui.tagline_12": "Racing through the dark...",
    "ui.tagline_13": "Fire and screams...",
    "ui.tagline_14": "Infection...",
    "ui.tagline_15": "The City of Masks...",
    "ui.tagline_16": "Blades sharpened in the shadows...",
    "ui.tagline_17": "A horrible task...",
    "ui.tagline_18": "Return through plague-barred gates...",
    "ui.tagline_19": "Halfway there...",
    "ui.tagline_20": "Under the light...",
    "ui.tagline_21": "Unleashed...",
});

// ── Deutsch (German) ─────────────────────────────────────────────────────────
// Note: game-specific terms (Macht-Decks, Tiefwald, etc.) should be verified
// against the official German edition before publishing.
STRINGS["de"] = Object.assign(STRINGS["de"] || {}, {
    "ui.new_campaign":         "Neue Kampagne",
    "ui.continue_campaign":    "Kampagne fortsetzen",
    "ui.might_decks":          "Macht-Decks",
    "ui.view_saved_data":      "Spielstand anzeigen",
    "ui.settings":             "Einstellungen",
    "ui.back":                 "Zur\u00fcck",
    "ui.select_chapter":       "Kapitel ausw\u00e4hlen",
    "ui.saved_data":           "Spielstand",
    "ui.copy_json":            "JSON kopieren",
    "ui.exit_chapter_select":  "Zur Kapitelauswahl",
    "ui.bug_report":           "Fehler melden",
    "ui.auto_scroll":          "Auto-Scrollen",
    "ui.auto_scroll_desc":     "Scrollt die Seite automatisch w\u00e4hrend der Erz\u00e4hlung. Manuelles Scrollen deaktiviert die Funktion f\u00fcr den aktuellen Abschnitt.",
    "ui.auto_narration":       "Erz\u00e4hlung automatisch starten",
    "ui.auto_narration_desc":  "Startet die Erz\u00e4hlung automatisch beim Laden eines neuen Abschnitts.",
    "ui.auto_next":            "N\u00e4chste Spur automatisch abspielen",
    "ui.auto_next_desc":       "Wechselt automatisch zur n\u00e4chsten Audiospur, wenn eine endet.",
    "ui.language":             "Sprache",
    "ui.language_desc":        "Wechselt die Sprache f\u00fcr Spieltext und Benutzeroberfl\u00e4che. Bei fehlenden \u00dcbersetzungen wird auf Englisch zur\u00fcckgegriffen.",
    "ui.file_bug_report":      "Fehler melden",
    "ui.bug_instructions":     "Kopiere die Debug-Informationen unten und f\u00fcge sie in ein neues GitHub-Issue ein:",
    "ui.copy_to_clipboard":    "In Zwischenablage kopieren",
    "ui.scroll_more":          "scrollen f\u00fcr mehr",
    "ui.autoscroll_paused":    "Auto-Scrollen pausiert \u00b7 zum Fortsetzen klicken",
    "ui.draw_history":         "Zughistorie",
    "ui.reshuffle_all":        "Alle neu mischen",
    "ui.clear":                "Leeren",
    "ui.draw_more":            "Mehr ziehen",
    "ui.clear_and_draw":       "Leeren & Ziehen",
    "ui.history":              "Verlauf",
    "ui.clear_history":        "Verlauf l\u00f6schen",
    "ui.tagline_1":  "Der Weg windet sich in den dunklen Wald...",
    "ui.tagline_2":  "Eine Versammlung an der Gebrochenen Eiche...",
    "ui.tagline_3":  "Die Ruhe vor dem Sturm...",
    "ui.tagline_4":  "Verloren und gejagt...",
    "ui.tagline_5":  "Ein verzweifelter R\u00fcckzug...",
    "ui.tagline_6":  "Etwas regt sich unter der Haut...",
    "ui.tagline_7":  "Ein d\u00fcsterer Marsch...",
    "ui.tagline_8":  "Ein Sieg, der sich wie eine Niederlage anf\u00fchlt...",
    "ui.tagline_9":  "Ersch\u00f6pft und vernarbt...",
    "ui.tagline_10": "In der Falle...",
    "ui.tagline_11": "Alte Feindschaften...",
    "ui.tagline_22": "Eine besondere Begegnung...",
    "ui.tagline_12": "Durch die Dunkelheit rasen...",
    "ui.tagline_13": "Feuer und Schreie...",
    "ui.tagline_14": "Infektion...",
    "ui.tagline_15": "Die Stadt der Masken...",
    "ui.tagline_16": "Im Schatten gesch\u00e4rfte Klingen...",
    "ui.tagline_17": "Eine schreckliche Aufgabe...",
    "ui.tagline_18": "R\u00fcckkehr durch seuchenverschlossene Tore...",
    "ui.tagline_19": "Auf halbem Weg...",
    "ui.tagline_20": "Im Licht...",
    "ui.tagline_21": "Entfesselt...",
});

// ── Italiano (Italian) ───────────────────────────────────────────────────────
// Note: game-specific terms should be verified against the official Italian
// edition before publishing.
STRINGS["it"] = Object.assign(STRINGS["it"] || {}, {
    "ui.new_campaign":         "Nuova Campagna",
    "ui.continue_campaign":    "Continua Campagna",
    "ui.might_decks":          "Mazzi Potere",
    "ui.view_saved_data":      "Visualizza Dati Salvati",
    "ui.settings":             "Impostazioni",
    "ui.back":                 "Indietro",
    "ui.select_chapter":       "Seleziona Capitolo",
    "ui.saved_data":           "Dati Salvati",
    "ui.copy_json":            "Copia JSON",
    "ui.exit_chapter_select":  "Torna alla Selezione Capitolo",
    "ui.bug_report":           "Segnala Bug",
    "ui.auto_scroll":          "Scorrimento Automatico",
    "ui.auto_scroll_desc":     "Scorre la pagina automaticamente durante la narrazione. Lo scorrimento manuale lo disabiliter\u00e0 per la sezione corrente.",
    "ui.auto_narration":       "Avvia Narrazione Automaticamente",
    "ui.auto_narration_desc":  "Avvia automaticamente la narrazione quando si carica una nuova sezione.",
    "ui.auto_next":            "Riproduci Traccia Successiva Automaticamente",
    "ui.auto_next_desc":       "Passa automaticamente alla traccia audio successiva quando una finisce.",
    "ui.language":             "Lingua",
    "ui.language_desc":        "Cambia la lingua del testo e dell\u2019interfaccia. Usa l\u2019inglese come fallback per le chiavi mancanti.",
    "ui.file_bug_report":      "Segnala un Bug",
    "ui.bug_instructions":     "Copia le informazioni di debug qui sotto e incollale in una nuova segnalazione su GitHub:",
    "ui.copy_to_clipboard":    "Copia negli Appunti",
    "ui.scroll_more":          "scorri per altro",
    "ui.autoscroll_paused":    "Scorrimento automatico in pausa \u00b7 clicca per riprendere",
    "ui.draw_history":         "Storico Pescate",
    "ui.reshuffle_all":        "Rimescola Tutto",
    "ui.clear":                "Cancella",
    "ui.draw_more":            "Pesca Altro",
    "ui.clear_and_draw":       "Cancella e Pesca",
    "ui.history":              "Cronologia",
    "ui.clear_history":        "Cancella Cronologia",
    "ui.tagline_1":  "La strada si snoda nel bosco oscuro...",
    "ui.tagline_2":  "Un raduno alla Quercia Spezzata...",
    "ui.tagline_3":  "La quiete prima della tempesta...",
    "ui.tagline_4":  "Persi e braccati...",
    "ui.tagline_5":  "Una disperata ritirata...",
    "ui.tagline_6":  "Qualcosa si agita sotto la pelle...",
    "ui.tagline_7":  "Una marcia sinistra...",
    "ui.tagline_8":  "Una vittoria che sembra una sconfitta...",
    "ui.tagline_9":  "Stanchi e segnati...",
    "ui.tagline_10": "In trappola...",
    "ui.tagline_11": "Vecchi rancori...",
    "ui.tagline_22": "Un incontro speciale...",
    "ui.tagline_12": "In corsa nel buio...",
    "ui.tagline_13": "Fuoco e urla...",
    "ui.tagline_14": "Infezione...",
    "ui.tagline_15": "La Citt\u00e0 delle Maschere...",
    "ui.tagline_16": "Lame affilate nell\u2019ombra...",
    "ui.tagline_17": "Un compito orribile...",
    "ui.tagline_18": "Ritorno attraverso i cancelli chiusi dalla peste...",
    "ui.tagline_19": "A met\u00e0 strada...",
    "ui.tagline_20": "Sotto la luce...",
    "ui.tagline_21": "Scatenato...",
});

// ── Français (French) ────────────────────────────────────────────────────────
// Note: game-specific terms should be verified against the official French
// edition before publishing.
STRINGS["fr"] = Object.assign(STRINGS["fr"] || {}, {
    "ui.new_campaign":         "Nouvelle Campagne",
    "ui.continue_campaign":    "Continuer la Campagne",
    "ui.might_decks":          "Decks de Puissance",
    "ui.view_saved_data":      "Voir les Donn\u00e9es Sauvegard\u00e9es",
    "ui.settings":             "Param\u00e8tres",
    "ui.back":                 "Retour",
    "ui.select_chapter":       "Choisir un Chapitre",
    "ui.saved_data":           "Donn\u00e9es Sauvegard\u00e9es",
    "ui.copy_json":            "Copier le JSON",
    "ui.exit_chapter_select":  "Retour \u00e0 la S\u00e9lection de Chapitre",
    "ui.bug_report":           "Signaler un Bug",
    "ui.auto_scroll":          "D\u00e9filement Automatique",
    "ui.auto_scroll_desc":     "Fait d\u00e9filer la page automatiquement pendant la narration. Faire d\u00e9filer manuellement le d\u00e9sactivera pour la section en cours.",
    "ui.auto_narration":       "D\u00e9marrer la Narration Automatiquement",
    "ui.auto_narration_desc":  "Lance la narration automatiquement lors du chargement d\u2019une nouvelle section.",
    "ui.auto_next":            "Lire la Piste Suivante Automatiquement",
    "ui.auto_next_desc":       "Passe automatiquement \u00e0 la piste audio suivante quand l\u2019une se termine.",
    "ui.language":             "Langue",
    "ui.language_desc":        "Change la langue du texte et de l\u2019interface. Revient \u00e0 l\u2019anglais pour les cl\u00e9s manquantes.",
    "ui.file_bug_report":      "Signaler un Bug",
    "ui.bug_instructions":     "Copiez les informations de d\u00e9bogage ci-dessous et collez-les dans un nouveau probl\u00e8me GitHub\u00a0:",
    "ui.copy_to_clipboard":    "Copier dans le Presse-papiers",
    "ui.scroll_more":          "d\u00e9filer pour voir plus",
    "ui.autoscroll_paused":    "D\u00e9filement automatique en pause \u00b7 cliquer pour reprendre",
    "ui.draw_history":         "Historique des Tirages",
    "ui.reshuffle_all":        "Tout Rebattre",
    "ui.clear":                "Effacer",
    "ui.draw_more":            "Piocher Plus",
    "ui.clear_and_draw":       "Effacer et Piocher",
    "ui.history":              "Historique",
    "ui.clear_history":        "Effacer l\u2019Historique",
    "ui.tagline_1":  "La route sinue dans la for\u00eat sombre...",
    "ui.tagline_2":  "Un rassemblement au Ch\u00eane Bris\u00e9...",
    "ui.tagline_3":  "Le calme avant la temp\u00eate...",
    "ui.tagline_4":  "Perdus et traqu\u00e9s...",
    "ui.tagline_5":  "Une retraite d\u00e9sesp\u00e9r\u00e9e...",
    "ui.tagline_6":  "Quelque chose remue sous la peau...",
    "ui.tagline_7":  "Une marche sinistre...",
    "ui.tagline_8":  "Une victoire qui ressemble \u00e0 une d\u00e9faite...",
    "ui.tagline_9":  "\u00c9puis\u00e9s et marqu\u00e9s...",
    "ui.tagline_10": "Pi\u00e9g\u00e9s...",
    "ui.tagline_11": "Vieilles ranc\u0153urs...",
    "ui.tagline_22": "Une rencontre sp\u00e9ciale...",
    "ui.tagline_12": "Course dans l\u2019obscurit\u00e9...",
    "ui.tagline_13": "Feu et cris...",
    "ui.tagline_14": "Infection...",
    "ui.tagline_15": "La Ville des Masques...",
    "ui.tagline_16": "Lames aiguis\u00e9es dans l\u2019ombre...",
    "ui.tagline_17": "Une t\u00e2che horrible...",
    "ui.tagline_18": "Retour \u00e0 travers les portes ferm\u00e9es par la peste...",
    "ui.tagline_19": "\u00c0 mi-chemin...",
    "ui.tagline_20": "Sous la lumi\u00e8re...",
    "ui.tagline_21": "D\u00e9cha\u00een\u00e9...",
});
